### ISSUE TITLE
`export` doesn't work with bass

### ISSUE THREAD

**Issue by pranaypratyush** [edc/bass#41]

**Comment by pranaypratyush** [comment]
What I meant is that `export` doesn't work when specifying path variables.

**Comment by edc** [comment]
@pranaypratyush sorry for the late reply. Make sure you quote `$PATH` if you are to append something to the path. For example, use `bass export PATH='$PATH:/usr/binx'` instead of `bass export PATH=$PATH:/usr/binx`. This is because fish will expand `$PATH` into space-separated items and it becomes invalid command in bash.
