### ISSUE TITLE
Inquiry: using exec as an alternative to bass

### ISSUE THREAD

**Issue by jorgebucaran** [edc/bass#67]
Hi @edc! 👋 

I've been running some experiments and noticed I could use `exec bash -c ...` instead of `bass` for doing the same thing. I was wondering if you were aware of this or if I was missing something. 

```fish
exec bash -c "$my_bash_cmds; exec fish"
```

One thing this code is missing is setting the exit status when `bash` fails, but I could live without that.

**Comment by edc** [comment]
Hi @jorgebucaran. That is a nice and elegant, and it did work well! Thanks for sharing! I will update README to mention that.

The downside I can see is that every time that line is run, you will start a new fish shell. So among other things, it will not have access to variable you set earlier.

```
 ~/Downloads/imports
$ set x 1
 ~/Downloads/imports
$ echo $x
1
 ~/Downloads/imports
$ exec bash -c "export y=2; exec fish"
Welcome to fish, the friendly interactive shell
 ~/Downloads/imports
$ echo $y
2
 ~/Downloads/imports
$ echo $x
```

You also cannot use it in a fish function or script, because it will terminate the fish process that is running the function/script.
