### ISSUE TITLE
Command 'python' not found

### ISSUE THREAD

**Issue by Talent30** [edc/bass#79]
I have python3 installed by default. Bass returns:
```
~ bass                                                                                         
Command 'python' not found, but can be installed with:

sudo apt install python3         # version 3.7.5-1, or
sudo apt install python          # version 2.7.17-1
sudo apt install python-minimal  # version 2.7.17-1

You also have python3 installed, you can run 'python3' instead.

~/.local/share/omf/pkg/bass/functions/bass.fish (line 10): 
  python (dirname (status -f))/__bass.py $bash_args 3>$script_file
  ^
in function “bass”
	called on standard input
```

**Comment by edc** [comment]
If you have python installed already, it is not on your `PATH`, and your shell cannot find it. You need to update your `PATH` to add the directory where python binary is. For example, if python is installed to `/opt/bin/python`, then you need to add this line to your fish config at `~/.config/fish/config.fish`:

```
set -x PATH /opt/bin $PATH
```

**Comment by nirvdrum** [comment]
@edc The problem here is there is no binary named `python` (at least in Ubuntu) if Python 3 is the only one installed. Ubuntu says they [will not symlink python to python3](https://wiki.ubuntu.com/Python/3), citing the advice provided in [PEP 394](https://legacy.python.org/dev/peps/pep-0394/). Without every user explicitly creating symlinks, bass does not work out of the box with Ubuntu 20.04+.

**Comment by nirvdrum** [comment]
Investigating this a bit more, the `bass.fish` properly invokes `python3` if available, but `__bass.py` does not. I'll open a PR.

**Comment by Talent30** [comment]
> 对此进行更多调查，如果有的话，`bass.fish`适当地调用`python3`，但`__bass.py`没有。我要开公关

Thank you very much!

**Comment by lougreenwood** [comment]
Im still getting this on a new Mac OS install (Ventura 13.1). Is this still a known issue?
